import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientLayout from "@/components/ClientLayout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
   <html lang="en">
  <body
    className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gradient-to-r from-[#03091DF2] via-[#132059] to-[#03091D]`}
  >
    <ClientLayout>{children}</ClientLayout>
  </body>
</html>

  );
}
